sudo: false

language: java

jdk:
  - oraclejdk11

before_install:
  - chmod +x mvnw

deploy:
  provider: heroku
  api-key:
    secure: "9a22e432-0bc3-46ff-b586-a98da6e45f3a"
  
script:
  - echo "scripts launched"
